---
title: "Lab10"
author: "Alice Zheng"
date: "11/2/2020"
output: html_document
---
## reading VCF data
```{r}
library(vcfR)
```

```{r}
data(vcfR_example)
vcf
```

## The meta region
```{r}
strwrap(vcf@meta[1:7])
```

```{r}
queryMETA(vcf)
```

```{r}
queryMETA(vcf, element = 'DP')
```

```{r}
queryMETA(vcf, element = 'FORMAT=<ID=DP')
```

## The fix region
```{r}
head(getFIX(vcf))
```

## The gt region
```{r}
vcf@gt[1:6, 1:4]
```

## Exercises Part 1

### 1.

?read.vcfR

### 2.
```{r}
queryMETA(vcf, element = 'AD')
```

### 3.
```{r}
tail(fix)
```

### 4.
```{r}
head(getQUAL(vcf))
plot(vcf)
```

### 5.
```{r}
colnames(vcf@gt)
```

## Analysis of genomic data

```{r}
library('vcfR')
vcf <- read.vcfR("pinfsc50_filtered.vcf")
```

```{r}
vcf
```

```{r}
library(adegenet)
```

```{r}
x <- vcfR2genlight(vcf)
x
```

```{r}
gt <- extract.gt(vcf, element = "GT")
gt[c(2,6,18), 1:3]
```

```{r}
t(as.matrix(x))[c(1,5,17), 1:3]
```

```{r}
pop(x) <- as.factor(c("us", "eu", "us", "af", "eu", "us", "mx", "eu", "eu", "sa", "mx", "sa", "us", "sa", "Pmir", "us", "eu", "eu"))
popNames(x)
```

```{r}
ploidy(x) <- 2
```

```{r}
x.dist <- dist(x)
```

```{r}
library(poppr)
x.dist <- poppr::bitwise.dist(x)
```

## Creating chromR objects
```{r}
library(vcfR)

vcf_file <- system.file("extdata", "pinf_sc50.vcf.gz", package = "pinfsc50")
dna_file <- system.file("extdata", "pinf_sc50.fasta", package = "pinfsc50")
gff_file <- system.file("extdata", "pinf_sc50.gff", package = "pinfsc50")

vcf <- read.vcfR(vcf_file, verbose = FALSE)
dna <- ape::read.dna(dna_file, format = "fasta")
gff <- read.table(gff_file, sep="\t", quote="")

chrom <- create.chromR(name="Supercontig", vcf=vcf, seq=dna, ann=gff, verbose=TRUE)
```

```{r}
chrom
plot(chrom)
```

```{r}
chromoqc(chrom, dp.alpha = 66)
```

```{r}
chrom <- proc.chromR(chrom, verbose = TRUE)
plot(chrom)
```

```{r}
chromoqc(chrom, dp.alpha = 66)
```

```{r}
vcf <- read.vcfR("pinfsc50_filtered.vcf", verbose = FALSE)
chrom <- create.chromR(name="Supercontig", vcf=vcf, seq=dna, ann=gff, verbose=FALSE)
chrom <- proc.chromR(chrom, verbose = FALSE)
chromoqc(chrom, dp.alpha = 66)
```

```{r}
head(chrom@var.info)
```

## Genetic differentiation
```{r}
data(vcfR_example)
pop <- as.factor(c("us", "eu", "us", "af", "eu", "us", "mx", "eu", "eu", "sa", "mx", "sa", "us", "sa", "Pmir", "us", "eu", "eu"))
myDiff <- genetic_diff(vcf, pops = pop, method = 'nei')
knitr::kable(head(myDiff[,1:15]))
```

```{r}
knitr::kable(head(myDiff[,16:19]))
```

```{r}
knitr::kable(round(colMeans(myDiff[,c(3:9,16,19)], na.rm = TRUE), digits = 3))
```

```{r}
library(reshape2)
library(ggplot2)

dpf <- melt(myDiff[,c(3:8,19)], varnames=c('Index', 'Sample'), value.name = 'Depth', na.rm=TRUE)
```

```{r}
p <- ggplot(dpf, aes(x=variable, y=Depth)) + geom_violin(fill="#2ca25f", adjust = 1.2)
p <- p + theme_bw()
p
```

## Exercises Part 2

### 1.
```{r}
plot(getPOS(vcf), myDiff$Gprimest,  pch = 20, col = "#1E90FF44", ylim = c(0, 1), xaxt = "n")
```

### 2.

there is a small sample size


### 3.
```{r}
chromoqc(chrom, dp.alpha = 66, xlim = c(4e05, 6e05))
```

### 4.
```{r}
queryMETA(vcf)
```



