---
title: "Lab3B"
author: "Alice Zheng"
date: "9/7/2020"
output: html_document
---

# Manipulating, analyzing and exporting data with tidyverse
```{r}
library("tidyverse")
surveys <- read_csv("data/portal_data_joined.csv")
```
```{r}

```

## Selecting columns and filtering rows
```{r}
select(surveys, plot_id, species_id, weight)
```

```{r}
select(surveys, -record_id, -species_id)
```
```{r}
filter(surveys, year == 1995)
```

## Pipes
```{r}
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
```

```{r}
surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

surveys_sml
```

## Challenge
```{r}
Surveys_new <- surveys %>%
  filter(year < 1995) %>%
  select(year, sex, weight)
Surveys_new
```

## Mutate
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000)
```
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

## Challenge
```{r}
surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  mutate(hindfoot_cm = hindfoot_length / 10) %>%
  filter(hindfoot_cm < 3) %>%
  select(species_id, hindfoot_cm)
```

## Split-apply-combine data analysis and the summarize() function
```{r}
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```

```{r}
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>% 
  tail()
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))
```

## Counting
```{r}
surveys %>%
    count(sex) 
```

```{r}
surveys %>%
    group_by(sex) %>%
    summarise(count = n())
```

```{r}
surveys %>%
    count(sex, sort = TRUE) 
```

```{r}
surveys %>%
  count(sex, species) 
```

```{r}
surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```

## Challenge
```{r}
surveys %>%
  count(plot_type)
```

```{r}
surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    group_by(species_id) %>%
    summarize(
        mean_hindfoot_length = mean(hindfoot_length),
        min_hindfoot_length = min(hindfoot_length),
        max_hindfoot_length = max(hindfoot_length),
        n = n()
    )
```

```{r}
surveys %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(year, genus, species, weight) %>%
    arrange(year)
```

## Reshaping with gather and spread
```{r}
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))
```
```{r}
str(surveys_gw)

```

```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
```

```{r}
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```

## Gathering
```{r}
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)

str(surveys_gather)
```

```{r}
surveys_spread %>%
  gather(key = "genus", value = "mean_weight", Baiomys:Spermophilus) %>%
  head()
```

## Challenge
```{r}
surveys_new <- surveys %>% 
  group_by(plot_id, year) %>% 
  summarize(n_genera = n_distinct(genus)) %>% 
  spread(year, n_genera) %>% 
  head()
surveys_new
```

```{r}
surveys_new %>% 
  gather("year", "n_genera", -plot_id) %>% 
  head()
```
```{r}
surveys_1 <- surveys %>% 
  gather("measurement", "value",hindfoot_length, weight)  
```

```{r}
surveys_1 %>% 
  group_by(measurement, year, plot_type) %>% 
  summarize(mean_value = mean(value, na.rm = TRUE)) %>% 
  spread(measurement, mean_value)
```

